package com.data.big.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 告警表
 *
 * @author 61471
 */
@Table(name = "alarm")
public class Alarm implements Serializable {
    /**
     * 编号
     */
    @Id
    private String id;

    /**
     * 1：告警0：正常
     */
    private Integer alarmState;

    /**
     * 告警结束时间
     */
    private Date endTime;

    /**
     * 告警开始时间
     */
    private Date beginTime;

    /**
     * 告警级别 告警级别１ ～ ３。１：重要告警；２：次要告警；３：一般告警
     */
    private Integer alarmLevel;

    /**
     * 告警类型
     */
    private String alarmType;

    /**
     * 告警源名称
     */
    private String name;

    /**
     * 告警资源ID
     */
    private String alarmResId;

    /**
     * 所属类型。0本级平台，1下级平台
     */
    private Integer belongType;

    /**
     * 所属接入服务编号
     */
    private String accessServerCode;

    /**
     * 处理状态。1未确认，2处理中，3待归档，4已归档,5消警
     */
    private Integer proState;

    /**
     * 目标信息
     */
    private String targetInfo;

    /**
     * 描述
     */
    private String descs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alarm
     *
     * @mbg.generated Fri May 08 15:17:23 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public Integer getAlarmState() {
        return alarmState;
    }

    public void setAlarmState(Integer alarmState) {
        this.alarmState = alarmState;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Date getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Integer getAlarmLevel() {
        return alarmLevel;
    }

    public void setAlarmLevel(Integer alarmLevel) {
        this.alarmLevel = alarmLevel;
    }

    public String getAlarmType() {
        return alarmType;
    }

    public void setAlarmType(String alarmType) {
        this.alarmType = alarmType == null ? null : alarmType.trim();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public String getAlarmResId() {
        return alarmResId;
    }

    public void setAlarmResId(String alarmResId) {
        this.alarmResId = alarmResId == null ? null : alarmResId.trim();
    }

    public Integer getBelongType() {
        return belongType;
    }

    public void setBelongType(Integer belongType) {
        this.belongType = belongType;
    }

    public String getAccessServerCode() {
        return accessServerCode;
    }

    public void setAccessServerCode(String accessServerCode) {
        this.accessServerCode = accessServerCode == null ? null : accessServerCode.trim();
    }

    public Integer getProState() {
        return proState;
    }

    public void setProState(Integer proState) {
        this.proState = proState;
    }

    public String getTargetInfo() {
        return targetInfo;
    }

    public void setTargetInfo(String targetInfo) {
        this.targetInfo = targetInfo == null ? null : targetInfo.trim();
    }

    public String getDescs() {
        return descs;
    }

    public void setDescs(String descs) {
        this.descs = descs == null ? null : descs.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", alarmState=").append(alarmState);
        sb.append(", endTime=").append(endTime);
        sb.append(", beginTime=").append(beginTime);
        sb.append(", alarmLevel=").append(alarmLevel);
        sb.append(", alarmType=").append(alarmType);
        sb.append(", name=").append(name);
        sb.append(", alarmResId=").append(alarmResId);
        sb.append(", belongType=").append(belongType);
        sb.append(", accessServerCode=").append(accessServerCode);
        sb.append(", proState=").append(proState);
        sb.append(", targetInfo=").append(targetInfo);
        sb.append(", descs=").append(descs);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}