package com.data.big.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "algorithmdata")
@Data
public class Algorithmdata implements Serializable {
    /**
     * 
     */
    @Id
    private String id;

    /**
     * 摄像机id
     */
    private String ipcid;

    /**
     * 分析类型
     */
    private String type;

    /**
     * 算法
     */
    private String algorithm;

    /**
     * 参数
     */
    private String param;

    /**
     * 
     */
    private String bz1;

    /**
     * 
     */
    private String bz2;

    /**
     * 
     */
    private String bz3;

    /**
     * 
     */
    private String bz4;

    /**
     * 
     */
    private String bz5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table algorithmdata
     *
     * @mbg.generated Mon Dec 21 16:59:02 CST 2020
     */
    private static final long serialVersionUID = 1L;


}