package com.data.big.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Table(name = "analysiresult")
@Data
public class Analysiresult implements Serializable {
    /**
     * 主键
     */
    @Id
    private String id;

    /**
     * 分析表的id,一个分析id对应多条结果
     */
    private String analysiid;

    /**
     * 结果信息
     */
    private String result;

    /**
     * 分析的结果地址
     */
    private String resulturl;

    /**
     * 类型区分进作业门，出作业门等分析场景
     */
    private String type;

    /**
     * 
     */
    private String bz1;

    /**
     * 
     */
    private String bz2;

    /**
     * 
     */
    private String bz3;

    /**
     * 
     */
    private String bz4;

    /**
     * 
     */
    private String bz5;

    /**
     * 工单id
     */
    private String gdid;

    /**
     * 创建时间
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table analysiresult
     *
     * @mbg.generated Mon Dec 21 16:59:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 第几页
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;

    /**
     * 每页个数
     */
    @Transient
    private List<Analysisvideo> analysiresultList;



    /**
     * 开始时间
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    @Transient
    private Date kssj;

    /**
     * 结束时间
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    @Transient
    private Date jssj;



    /**
     * 分析的方法例：作业门，行人等
     */
    @Transient
    private String algorithm;
}