package com.data.big.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;
@Table(name = "analysisvideo")
@Data
public class Analysisvideo implements Serializable {
    /**
     * 主键id
     */
    @Id
    private String id;

    /**
     * 区分分析的是实时摄像头还是下载好的文化0实时1历史2本地文件
     */
    private String type;

    /**
     * 开始时间
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    private Date kssj;

    /**
     * 结束时间
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    private Date jssj;

    /**
     * 分析目标的id，type为0，1时targetid为摄像机的id，2时为video_file的id
     */
    private String targetid;

    /**
     * 数据入库的时间
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    private Date rksj;

    /**
     * 0未完成1进行中2已完成
     */
    private String status;

    /**
     * 分析的方法,例：作业门，行人等
     */
    private String algorithm;

    /**
     * 
     */
    private String gdid;

    /**
     * 
     */
    private String bz1;

    /**
     * 
     */
    private String bz2;

    /**
     * 
     */
    private String bz3;

    /**
     * 
     */
    private String bz4;

    /**
     * 
     */
    private String bz5;

    /**
     * 创建时间
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table analysisvideo
     *
     * @mbg.generated Mon Dec 21 17:07:16 CST 2020
     */
    private static final long serialVersionUID = 1L;
    /**
     * 第几页
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;
}