package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "camera")
public class Camera implements Serializable {
    /**
     * 设备标识
     */
    @Id
    private String deviceId;

    /**
     * 设备名称
     */
    private String deviceName;

    /**
     * 所属节点ID
     */
    private String nodeId;

    /**
     * 设备类型
     */
    private String deviceType;

    /**
     * 设备厂商
     */
    private String manufacturer;

    /**
     * 相机类型
     */
    private String cameraType;

    /**
     * 分辨率
     */
    private String cameraDpi;

    /**
     * IP地址
     */
    private String ipAddr;

    /**
     * 端口
     */
    private String ipPort;

    /**
     * 用户名
     */
    private String username;

    /**
     * 密码
     */
    private String password;

    /**
     * 安装时间
     */
    private String installTime;

    /**
     * 业务归属
     */
    private String affiliation;

    /**
     * 行别
     */
    private String upDown;

    /**
     * 线路
     */
    private String associatedLine;

    /**
     * 里程公里标
     */
    private String kMark;

    /**
     * 接入站点
     */
    private String joinStation;

    /**
     * 监视方向
     */
    private String direction;

    /**
     * 监视目标或安装位置
     */
    private String targetLocation;

    /**
     * 目录分类
 1、车站咽喉；
 2、公跨铁；
 3、供电/电力设施；
 4、通信设施；
 5、信号设施；
 6、线路；
 7、信息设施；
 8、运转室；
 9、救援疏散通道；
 10、车站；
 11、其它部位
 
     */
    private String catalogue;

    /**
     * 经度
     */
    private String longitude;

    /**
     * 纬度
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camera
     *
     * @mbg.generated Mon Sep 21 15:07:16 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    public String getCameraType() {
        return cameraType;
    }

    public void setCameraType(String cameraType) {
        this.cameraType = cameraType == null ? null : cameraType.trim();
    }

    public String getCameraDpi() {
        return cameraDpi;
    }

    public void setCameraDpi(String cameraDpi) {
        this.cameraDpi = cameraDpi == null ? null : cameraDpi.trim();
    }

    public String getIpAddr() {
        return ipAddr;
    }

    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    public String getIpPort() {
        return ipPort;
    }

    public void setIpPort(String ipPort) {
        this.ipPort = ipPort == null ? null : ipPort.trim();
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getInstallTime() {
        return installTime;
    }

    public void setInstallTime(String installTime) {
        this.installTime = installTime == null ? null : installTime.trim();
    }

    public String getAffiliation() {
        return affiliation;
    }

    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation == null ? null : affiliation.trim();
    }

    public String getUpDown() {
        return upDown;
    }

    public void setUpDown(String upDown) {
        this.upDown = upDown == null ? null : upDown.trim();
    }

    public String getAssociatedLine() {
        return associatedLine;
    }

    public void setAssociatedLine(String associatedLine) {
        this.associatedLine = associatedLine == null ? null : associatedLine.trim();
    }

    public String getkMark() {
        return kMark;
    }

    public void setkMark(String kMark) {
        this.kMark = kMark == null ? null : kMark.trim();
    }

    public String getJoinStation() {
        return joinStation;
    }

    public void setJoinStation(String joinStation) {
        this.joinStation = joinStation == null ? null : joinStation.trim();
    }

    public String getDirection() {
        return direction;
    }

    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    public String getTargetLocation() {
        return targetLocation;
    }

    public void setTargetLocation(String targetLocation) {
        this.targetLocation = targetLocation == null ? null : targetLocation.trim();
    }

    public String getCatalogue() {
        return catalogue;
    }

    public void setCatalogue(String catalogue) {
        this.catalogue = catalogue == null ? null : catalogue.trim();
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deviceId=").append(deviceId);
        sb.append(", deviceName=").append(deviceName);
        sb.append(", nodeId=").append(nodeId);
        sb.append(", deviceType=").append(deviceType);
        sb.append(", manufacturer=").append(manufacturer);
        sb.append(", cameraType=").append(cameraType);
        sb.append(", cameraDpi=").append(cameraDpi);
        sb.append(", ipAddr=").append(ipAddr);
        sb.append(", ipPort=").append(ipPort);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", installTime=").append(installTime);
        sb.append(", affiliation=").append(affiliation);
        sb.append(", upDown=").append(upDown);
        sb.append(", associatedLine=").append(associatedLine);
        sb.append(", kMark=").append(kMark);
        sb.append(", joinStation=").append(joinStation);
        sb.append(", direction=").append(direction);
        sb.append(", targetLocation=").append(targetLocation);
        sb.append(", catalogue=").append(catalogue);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}