package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "camerainfo")
public class Camerainfo implements Serializable {
    /**
     * 设备标识
     */
    @Id
    private String deviceId;

    /**
     * 设备名称
     */
    private String deviceName;

    /**
     * 所属节点ID
     */
    private String nodeId;

    /**
     * 设备类型
     */
    private String deviceType;

    /**
     * 设备厂商
     */
    private String manufacturer;

    /**
     * IP地址
     */
    private String ipAddr;

    /**
     * 端口
     */
    private String ipPort;

    /**
     * 用户名
     */
    private String username;

    /**
     * 密码
     */
    private String password;

    /**
     * 安装时间
     */
    private String installTime;

    /**
     * 业务归属
     */
    private String affiliation;

    /**
     * 行别
     */
    private String upDown;

    /**
     * 线路
     */
    private String associatedLine;

    /**
     * 里程公里标
     */
    private Integer kMark;

    /**
     * 经度
     */
    private String longitude;

    /**
     * 纬度
     */
    private String latitude;

    /**
     * 安装区域站内或区间
     */
    private String region;

    /**
     * 位置类型股道、大厅
     */
    private String locationType;

    /**
     * 位置编号
     */
    private String locationNum;

    /**
     * 观测范围半径
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camerainfo
     *
     * @mbg.generated Wed Oct 14 17:10:58 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    public String getDeviceName() {
        return deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    public String getIpAddr() {
        return ipAddr;
    }

    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr == null ? null : ipAddr.trim();
    }

    public String getIpPort() {
        return ipPort;
    }

    public void setIpPort(String ipPort) {
        this.ipPort = ipPort == null ? null : ipPort.trim();
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    public String getInstallTime() {
        return installTime;
    }

    public void setInstallTime(String installTime) {
        this.installTime = installTime == null ? null : installTime.trim();
    }

    public String getAffiliation() {
        return affiliation;
    }

    public void setAffiliation(String affiliation) {
        this.affiliation = affiliation == null ? null : affiliation.trim();
    }

    public String getUpDown() {
        return upDown;
    }

    public void setUpDown(String upDown) {
        this.upDown = upDown == null ? null : upDown.trim();
    }

    public String getAssociatedLine() {
        return associatedLine;
    }

    public void setAssociatedLine(String associatedLine) {
        this.associatedLine = associatedLine == null ? null : associatedLine.trim();
    }

    public Integer getkMark() {
        return kMark;
    }

    public void setkMark(Integer kMark) {
        this.kMark = kMark;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    public String getLocationType() {
        return locationType;
    }

    public void setLocationType(String locationType) {
        this.locationType = locationType == null ? null : locationType.trim();
    }

    public String getLocationNum() {
        return locationNum;
    }

    public void setLocationNum(String locationNum) {
        this.locationNum = locationNum == null ? null : locationNum.trim();
    }

    public String getArea() {
        return area;
    }

    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deviceId=").append(deviceId);
        sb.append(", deviceName=").append(deviceName);
        sb.append(", nodeId=").append(nodeId);
        sb.append(", deviceType=").append(deviceType);
        sb.append(", manufacturer=").append(manufacturer);
        sb.append(", ipAddr=").append(ipAddr);
        sb.append(", ipPort=").append(ipPort);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", installTime=").append(installTime);
        sb.append(", affiliation=").append(affiliation);
        sb.append(", upDown=").append(upDown);
        sb.append(", associatedLine=").append(associatedLine);
        sb.append(", kMark=").append(kMark);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", region=").append(region);
        sb.append(", locationType=").append(locationType);
        sb.append(", locationNum=").append(locationNum);
        sb.append(", area=").append(area);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}