package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "Camerastatus")
public class Camerastatus implements Serializable {
    /**
     * 主键guid
     */
    @Id
    private String id;

    /**
     * 设备标识 铁标16位设备编码
     */
    private String deviceId;

    /**
     * 时间
     */
    private String statusTime;

    /**
     * 在线状态 1-在线，0-离线
     */
    private String onlineStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table camerastatus
     *
     * @mbg.generated Wed Aug 12 10:23:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    public String getStatusTime() {
        return statusTime;
    }

    public void setStatusTime(String statusTime) {
        this.statusTime = statusTime == null ? null : statusTime.trim();
    }

    public String getOnlineStatus() {
        return onlineStatus;
    }

    public void setOnlineStatus(String onlineStatus) {
        this.onlineStatus = onlineStatus == null ? null : onlineStatus.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", deviceId=").append(deviceId);
        sb.append(", statusTime=").append(statusTime);
        sb.append(", onlineStatus=").append(onlineStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}