package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
@Table(name = "foreign_body_alarm")
public class ForeignBodyAlarm implements Serializable {
    /**
     * id
     */
    @Id
    private String id;

    /**
     * 监控单元编码 监控单元公里标，单位m
     */
    private String controlUnitCode;

    /**
     * 监测点编码 监测点公里标，单位m
     */
    private String checkLocaleCode;

    /**
     * 电网1继电器状态  0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String grid1RelayStatus;

    /**
     * 电网2继电器状态 0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String grid2RelayStatus;

    /**
     * 上行临时行车继电器状态 0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String upTemporaryRelayStatus;

    /**
     * 下行临时行车继电器状态 0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String downTemporaryRelayStatus;

    /**
     * 现场恢复继电器状态 0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String sceneRecoveryRelayStatus;

    /**
     *  调度恢复继电器状态  0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String dispatchRecoveryRelayStatus;

    /**
     * 电网1远程试验继电器状态   0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String grid1ExperimentRelayStatus;

    /**
     * 电网2远程试验继电器状态  0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String grid2ExperimentRelayStatus;

    /**
     * 上行列控继电器状态 0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String upControlRelayStatus;

    /**
     * 下行列控继电器状态 0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String dispatchControlRelayStatus;

    /**
     * 报警继电器状态  0x00：吸起，0x01：落下，0x02：不可用，0x03：无回采
     */
    private String alarmRelayStatus;

    /**
     * 数据长度 影响区间字节长度
     */
    private String influenceDataLength;

    /**
     * 影响区间  UTF-8编码格式，车站名称~车站名称
     */
    private String influenceInterval;

    /**
     * 数据长度 控轨区段数据长度
     */
    private String trackDataLength;

    /**
     * 控轨区段 ASCII码，上行轨道号+“|”+下行轨道号
     */
    private String trackInterval;

    /**
     * 预留1 精度转换倍率（0.1m/s的倍率），举例：精度为0.1m/s，赋值1，精度为0.01m/s，赋值10
     */
    private String reserve1;

    /**
     *  预留2 无符号整型，0-999（毫秒）
     */
    private String reserve2;

    /**
     * 报警标志 0x01：电网1故障，0x02：电网2故障，0x03：双电网报警，0x04：电网1故障恢复，0x05：电网2故障恢复，0x06：脱离监控，0x07：其他类型
     */
    private String alarmSign;

    /**
     * 创建时间
     */
    private Date date;

    /**
     * 报警状态
     */
    private String alarmStatus;

    /**
     * 报警解除时间
     */
    private Date relieveTime;

    /**
     * 视频上传状态
     */
    private String videoUpStatus;

    /**
     * 检测点公里标   k444x888 形式
     */
    private String checkLocaleKilometre;

    /**
     * 原始数据
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table foreign_body_alarm
     *
     * @mbg.generated Thu Sep 03 09:01:39 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getControlUnitCode() {
        return controlUnitCode;
    }

    public void setControlUnitCode(String controlUnitCode) {
        this.controlUnitCode = controlUnitCode == null ? null : controlUnitCode.trim();
    }

    public String getCheckLocaleCode() {
        return checkLocaleCode;
    }

    public void setCheckLocaleCode(String checkLocaleCode) {
        this.checkLocaleCode = checkLocaleCode == null ? null : checkLocaleCode.trim();
    }

    public String getGrid1RelayStatus() {
        return grid1RelayStatus;
    }

    public void setGrid1RelayStatus(String grid1RelayStatus) {
        this.grid1RelayStatus = grid1RelayStatus == null ? null : grid1RelayStatus.trim();
    }

    public String getGrid2RelayStatus() {
        return grid2RelayStatus;
    }

    public void setGrid2RelayStatus(String grid2RelayStatus) {
        this.grid2RelayStatus = grid2RelayStatus == null ? null : grid2RelayStatus.trim();
    }

    public String getUpTemporaryRelayStatus() {
        return upTemporaryRelayStatus;
    }

    public void setUpTemporaryRelayStatus(String upTemporaryRelayStatus) {
        this.upTemporaryRelayStatus = upTemporaryRelayStatus == null ? null : upTemporaryRelayStatus.trim();
    }

    public String getDownTemporaryRelayStatus() {
        return downTemporaryRelayStatus;
    }

    public void setDownTemporaryRelayStatus(String downTemporaryRelayStatus) {
        this.downTemporaryRelayStatus = downTemporaryRelayStatus == null ? null : downTemporaryRelayStatus.trim();
    }

    public String getSceneRecoveryRelayStatus() {
        return sceneRecoveryRelayStatus;
    }

    public void setSceneRecoveryRelayStatus(String sceneRecoveryRelayStatus) {
        this.sceneRecoveryRelayStatus = sceneRecoveryRelayStatus == null ? null : sceneRecoveryRelayStatus.trim();
    }

    public String getDispatchRecoveryRelayStatus() {
        return dispatchRecoveryRelayStatus;
    }

    public void setDispatchRecoveryRelayStatus(String dispatchRecoveryRelayStatus) {
        this.dispatchRecoveryRelayStatus = dispatchRecoveryRelayStatus == null ? null : dispatchRecoveryRelayStatus.trim();
    }

    public String getGrid1ExperimentRelayStatus() {
        return grid1ExperimentRelayStatus;
    }

    public void setGrid1ExperimentRelayStatus(String grid1ExperimentRelayStatus) {
        this.grid1ExperimentRelayStatus = grid1ExperimentRelayStatus == null ? null : grid1ExperimentRelayStatus.trim();
    }

    public String getGrid2ExperimentRelayStatus() {
        return grid2ExperimentRelayStatus;
    }

    public void setGrid2ExperimentRelayStatus(String grid2ExperimentRelayStatus) {
        this.grid2ExperimentRelayStatus = grid2ExperimentRelayStatus == null ? null : grid2ExperimentRelayStatus.trim();
    }

    public String getUpControlRelayStatus() {
        return upControlRelayStatus;
    }

    public void setUpControlRelayStatus(String upControlRelayStatus) {
        this.upControlRelayStatus = upControlRelayStatus == null ? null : upControlRelayStatus.trim();
    }

    public String getDispatchControlRelayStatus() {
        return dispatchControlRelayStatus;
    }

    public void setDispatchControlRelayStatus(String dispatchControlRelayStatus) {
        this.dispatchControlRelayStatus = dispatchControlRelayStatus == null ? null : dispatchControlRelayStatus.trim();
    }

    public String getAlarmRelayStatus() {
        return alarmRelayStatus;
    }

    public void setAlarmRelayStatus(String alarmRelayStatus) {
        this.alarmRelayStatus = alarmRelayStatus == null ? null : alarmRelayStatus.trim();
    }

    public String getInfluenceDataLength() {
        return influenceDataLength;
    }

    public void setInfluenceDataLength(String influenceDataLength) {
        this.influenceDataLength = influenceDataLength == null ? null : influenceDataLength.trim();
    }

    public String getInfluenceInterval() {
        return influenceInterval;
    }

    public void setInfluenceInterval(String influenceInterval) {
        this.influenceInterval = influenceInterval == null ? null : influenceInterval.trim();
    }

    public String getTrackDataLength() {
        return trackDataLength;
    }

    public void setTrackDataLength(String trackDataLength) {
        this.trackDataLength = trackDataLength == null ? null : trackDataLength.trim();
    }

    public String getTrackInterval() {
        return trackInterval;
    }

    public void setTrackInterval(String trackInterval) {
        this.trackInterval = trackInterval == null ? null : trackInterval.trim();
    }

    public String getReserve1() {
        return reserve1;
    }

    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    public String getReserve2() {
        return reserve2;
    }

    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    public String getAlarmSign() {
        return alarmSign;
    }

    public void setAlarmSign(String alarmSign) {
        this.alarmSign = alarmSign == null ? null : alarmSign.trim();
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getAlarmStatus() {
        return alarmStatus;
    }

    public void setAlarmStatus(String alarmStatus) {
        this.alarmStatus = alarmStatus == null ? null : alarmStatus.trim();
    }

    public Date getRelieveTime() {
        return relieveTime;
    }

    public void setRelieveTime(Date relieveTime) {
        this.relieveTime = relieveTime;
    }

    public String getVideoUpStatus() {
        return videoUpStatus;
    }

    public void setVideoUpStatus(String videoUpStatus) {
        this.videoUpStatus = videoUpStatus == null ? null : videoUpStatus.trim();
    }

    public String getCheckLocaleKilometre() {
        return checkLocaleKilometre;
    }

    public void setCheckLocaleKilometre(String checkLocaleKilometre) {
        this.checkLocaleKilometre = checkLocaleKilometre == null ? null : checkLocaleKilometre.trim();
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", controlUnitCode=").append(controlUnitCode);
        sb.append(", checkLocaleCode=").append(checkLocaleCode);
        sb.append(", grid1RelayStatus=").append(grid1RelayStatus);
        sb.append(", grid2RelayStatus=").append(grid2RelayStatus);
        sb.append(", upTemporaryRelayStatus=").append(upTemporaryRelayStatus);
        sb.append(", downTemporaryRelayStatus=").append(downTemporaryRelayStatus);
        sb.append(", sceneRecoveryRelayStatus=").append(sceneRecoveryRelayStatus);
        sb.append(", dispatchRecoveryRelayStatus=").append(dispatchRecoveryRelayStatus);
        sb.append(", grid1ExperimentRelayStatus=").append(grid1ExperimentRelayStatus);
        sb.append(", grid2ExperimentRelayStatus=").append(grid2ExperimentRelayStatus);
        sb.append(", upControlRelayStatus=").append(upControlRelayStatus);
        sb.append(", dispatchControlRelayStatus=").append(dispatchControlRelayStatus);
        sb.append(", alarmRelayStatus=").append(alarmRelayStatus);
        sb.append(", influenceDataLength=").append(influenceDataLength);
        sb.append(", influenceInterval=").append(influenceInterval);
        sb.append(", trackDataLength=").append(trackDataLength);
        sb.append(", trackInterval=").append(trackInterval);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", alarmSign=").append(alarmSign);
        sb.append(", date=").append(date);
        sb.append(", alarmStatus=").append(alarmStatus);
        sb.append(", relieveTime=").append(relieveTime);
        sb.append(", videoUpStatus=").append(videoUpStatus);
        sb.append(", checkLocaleKilometre=").append(checkLocaleKilometre);
        sb.append(", data=").append(data);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}