package com.data.big.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Table(name = "img_task")
@Data
public class ImgTask implements Serializable {
    /**
     * 主键guid
     */
    @Id
    private String id;

    /**
     * 摄像头ID
     */
    private String ipcid;

    /**
     * 存储任务开始的日期 例：2020-11-21
     */
    private String ksrq;

    /**
     * 存储任务结束的日期
     */
    private String jsrq;

    /**
     * 0未下载1已下载2上传中
 3已上传200问题任务
     */
    private String status;

    /**
     * 下载时间
     */
    private String loadtime;

    /**
     * 本地存储路径
     */
    private String path;

    /**
     * 文件名称
     */
    private String filename;

    /**
     * 文件ID
     */
    private String fileid;

    /**
     * 文件上传时间
     */
    private String uptime;

    /**
     * 备注
     */
    private String bz;

    /**
     * 视频类型名
     */
    private String videoType;

    /**
     * 组id代表同一次下单的任务
     */
    private String groupId;

    /**
     * 抓拍时间(存储抓拍的时间点)
     */
    private String zpsj;

    /**
     * 抓拍日期（持续时间与抓拍时间的组合）
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date zprq;
    /**
     * 第几页
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;
    /**
     * 每页个数
     */
    @Transient
    private Camera camera;
    /**
     * 每页个数
     */
    @Transient
    private String cameraType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table img_task
     *
     * @mbg.generated Fri Nov 20 11:31:21 CST 2020
     */
    private static final long serialVersionUID = 1L;


    /**
     * 每页个数
     */
    @Transient
    private String videoTypeTag;
    /**
     * 每页个数
     */
    @Transient
    private String cameraName;
    /**
     * 每页个数
     */
    @Transient
    private List<VideoTag> videoTags;

}