package com.data.big.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.List;

@Table(name = "ipcseelocation")
@Data
public class Ipcseelocation implements Serializable {
    /**
     * 主键
     */
    @Id
    private String id;

    /**
     * 世界坐标x
     */
    private String x;

    /**
     * 世界坐标y
     */
    private String y;

    /**
     * 世界坐标z
     */
    private String z;

    /**
     * 方向
     */
    private String heading;

    /**
     * 倾斜角度
     */
    private String pitch;

    /**
     * 围绕x轴旋转
     */
    private String roll;

    /**
     * 
     */
    private String ipcid;

    /**
     * 场景类型 例：观测进入隧道、观测行车等
     */
    private String scenetype;

    /**
     * 
     */
    private Integer kmStart;

    /**
     * 
     */
    private Integer kmEnd;

    /**
     * 线名课题默认京包客专
     */
    private String xm;

    /**
     * 行别：上下行或者京向 张向
     */
    private String xb;

    /**
     * 
     */
    private String bz1;

    /**
     * 
     */
    private String bz2;

    /**
     * 
     */
    private String bz3;

    /**
     * 
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ipcseelocation
     *
     * @mbg.generated Mon Nov 30 08:42:49 CST 2020
     */
    private static final long serialVersionUID = 1L;


    /**
     * 第几页
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;
    /**
     * 每页个数
     */
    @Transient
    private List<Screenresolving> screenresolvingList;
    /**
     * 每页个数
     */
    @Transient
    private Camera camera;
    /**
     * 摄像机
     */
    @Transient
    private String cameraName;
    /**
     * 摄像机名称
     */
    @Transient
    private String ipcsTag;
    /**
     * 摄像机类型
     */
    @Transient
    private String cameraType;
}