package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "method_type")
public class MethodType implements Serializable {
    /**
     * 
     */
    @Id
    private Integer id;

    /**
     * 名称
     */
    private String methodName;

    /**
     * 描述
     */
    private String methodDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table method_type
     *
     * @mbg.generated Fri Sep 25 10:08:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMethodName() {
        return methodName;
    }

    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    public String getMethodDesc() {
        return methodDesc;
    }

    public void setMethodDesc(String methodDesc) {
        this.methodDesc = methodDesc == null ? null : methodDesc.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", methodName=").append(methodName);
        sb.append(", methodDesc=").append(methodDesc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}