package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

@Table(name = "Nodeinfo")
public class Nodeinfo implements Serializable {
    /**
     * 节点ID
     */
    @Id
    private String nodeId;

    /**
     * 节点名称
     */
    private String nodeName;

    /**
     * 父节点
     */
    private String nodeParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nodeinfo
     *
     * @mbg.generated Tue Aug 11 17:08:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    public String getNodeParent() {
        return nodeParent;
    }

    public void setNodeParent(String nodeParent) {
        this.nodeParent = nodeParent == null ? null : nodeParent.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", nodeId=").append(nodeId);
        sb.append(", nodeName=").append(nodeName);
        sb.append(", nodeParent=").append(nodeParent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}