package com.data.big.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
@Table(name = "screenresolving")
@Data
public class Screenresolving implements Serializable {
    /**
     * 
     */
    @Id
    private String id;

    /**
     * 外键ipcseelocation表的主键
     */
    private String fid;

    /**
     * 长
     */
    private String length;

    /**
     * 宽
     */
    private String width;

    /**
     * 屏幕分辨率
     */
    private String resolving;

    /**
     * 播放画面左上角的横坐标
     */
    private String leftX;

    /**
     * 播放画面左上角的纵坐标
     */
    private String leftY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table screenresolving
     *
     * @mbg.generated Mon Nov 30 08:43:13 CST 2020
     */
    private static final long serialVersionUID = 1L;


    /**
     * 第几页
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;
    /**
     * 每页个数
     */
    @Transient
    private Ipcseelocation ipcseelocation;
}