package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
@Table(name = "sensor_status_alarm")
public class SensorStatusAlarm implements Serializable {
    /**
     * id
     */
    @Id
    private String id;

    /**
     * 监控单元编码 监控单元公里标，单位m
     */
    private String controlUnitCode;

    /**
     * 监测点编码 监测点公里标，单位m
     */
    private String checkLocaleCode;

    /**
     * 监测点类型 0x00：风；0x01：雨；0x02：雪；0x04：地震
     */
    private String checkLocaleType;

    /**
     * 传感器通信状态 两位表示一个传感器状态，从低位到高位写入； 0表示正常、1表示故障、2表示未知、3表示失联；
     */
    private String sensorCommunicationStatus;

    /**
     * 故障类型 0表示故障开始，1表示故障结束（所有故障恢复）
     */
    private String faultType;

    /**
     * 传感器供电状态  两位表示一个传感器状态，从低位到高位写入； 0表示正常、1表示故障、2表示未知、3表示失联；
     */
    private String sensorPowerSupplyStatus;

    /**
     * 预留1 精度转换倍率（0.1m/s的倍率），举例：精度为0.1m/s，赋值1，精度为0.01m/s，赋值10
     */
    private String reserve1;

    /**
     *  预留2 无符号整型，0-999（毫秒）
     */
    private String reserve2;

    /**
     * 创建时间
     */
    private Date date;

    /**
     * 报警状态
     */
    private String alarmStatus;

    /**
     * 报警解除时间
     */
    private Date relieveTime;

    /**
     * 视频上传状态
     */
    private String videoUpStatus;

    /**
     * 检测点公里标   k444x888 形式
     */
    private String checkLocaleKilometre;

    /**
     * 原始数据
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sensor_status_alarm
     *
     * @mbg.generated Thu Sep 03 09:12:07 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getControlUnitCode() {
        return controlUnitCode;
    }

    public void setControlUnitCode(String controlUnitCode) {
        this.controlUnitCode = controlUnitCode == null ? null : controlUnitCode.trim();
    }

    public String getCheckLocaleCode() {
        return checkLocaleCode;
    }

    public void setCheckLocaleCode(String checkLocaleCode) {
        this.checkLocaleCode = checkLocaleCode == null ? null : checkLocaleCode.trim();
    }

    public String getCheckLocaleType() {
        return checkLocaleType;
    }

    public void setCheckLocaleType(String checkLocaleType) {
        this.checkLocaleType = checkLocaleType == null ? null : checkLocaleType.trim();
    }

    public String getSensorCommunicationStatus() {
        return sensorCommunicationStatus;
    }

    public void setSensorCommunicationStatus(String sensorCommunicationStatus) {
        this.sensorCommunicationStatus = sensorCommunicationStatus == null ? null : sensorCommunicationStatus.trim();
    }

    public String getFaultType() {
        return faultType;
    }

    public void setFaultType(String faultType) {
        this.faultType = faultType == null ? null : faultType.trim();
    }

    public String getSensorPowerSupplyStatus() {
        return sensorPowerSupplyStatus;
    }

    public void setSensorPowerSupplyStatus(String sensorPowerSupplyStatus) {
        this.sensorPowerSupplyStatus = sensorPowerSupplyStatus == null ? null : sensorPowerSupplyStatus.trim();
    }

    public String getReserve1() {
        return reserve1;
    }

    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    public String getReserve2() {
        return reserve2;
    }

    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getAlarmStatus() {
        return alarmStatus;
    }

    public void setAlarmStatus(String alarmStatus) {
        this.alarmStatus = alarmStatus == null ? null : alarmStatus.trim();
    }

    public Date getRelieveTime() {
        return relieveTime;
    }

    public void setRelieveTime(Date relieveTime) {
        this.relieveTime = relieveTime;
    }

    public String getVideoUpStatus() {
        return videoUpStatus;
    }

    public void setVideoUpStatus(String videoUpStatus) {
        this.videoUpStatus = videoUpStatus == null ? null : videoUpStatus.trim();
    }

    public String getCheckLocaleKilometre() {
        return checkLocaleKilometre;
    }

    public void setCheckLocaleKilometre(String checkLocaleKilometre) {
        this.checkLocaleKilometre = checkLocaleKilometre == null ? null : checkLocaleKilometre.trim();
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", controlUnitCode=").append(controlUnitCode);
        sb.append(", checkLocaleCode=").append(checkLocaleCode);
        sb.append(", checkLocaleType=").append(checkLocaleType);
        sb.append(", sensorCommunicationStatus=").append(sensorCommunicationStatus);
        sb.append(", faultType=").append(faultType);
        sb.append(", sensorPowerSupplyStatus=").append(sensorPowerSupplyStatus);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", date=").append(date);
        sb.append(", alarmStatus=").append(alarmStatus);
        sb.append(", relieveTime=").append(relieveTime);
        sb.append(", videoUpStatus=").append(videoUpStatus);
        sb.append(", checkLocaleKilometre=").append(checkLocaleKilometre);
        sb.append(", data=").append(data);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}