package com.data.big.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "sgjh")
@Data
public class Sgjh implements Serializable {
    /**
     * id
     */
    @Id
    private String id;

    /**
     * 日计划号
     */
    private String rjhh;

    /**
     * 计划状态 "-1 驳回", "0车间上报", "2段审批", "3计划下达", "4车间派单", "6计划销号"	
     */
    private String sbztw;

    /**
     * 点内外(0点内 1点外 2超临修)
     */
    private String zylx;

    /**
     * 作业日期
     */
    private String zyrq;

    /**
     * 计划开始时间
     */
    private String jhqssj;

    /**
     * 计划终止时间
     */
    private String jhzzsj;

    /**
     * 施工等级
     */
    private String zydj;

    /**
     * 线名
     */
    private String xm;

    /**
     * 行别
     */
    private String xb;

    /**
     * 作业位置：区间/站内
     */
    private String zywz;

    /**
     * 起始车站
     */
    private String qschzm;

    /**
     * 终止车站
     */
    private String zzchzm;

    /**
     * 作业起始里程
     */
    private String zyqslc;

    /**
     * 作业终止里程
     */
    private String zyzzlc;

    /**
     * 主体单位
     */
    private String sgztdw;

    /**
     * 配合单位
     */
    private String phdw;

    /**
     * 施工负责人
     */
    private String fzrname;

    /**
     * 限速及行车方式
     */
    private String xsjxcfs;

    /**
     * 路用车信息
     */
    private String lycxx;

    /**
     * 添加任务状态 0未添加 1以添加
     */
    private String status;

    /**
     * 施工项目
     */
    private String zyxm;

    /**
     * 施工内容及影响范围
     */
    private String sgnrjyxfw;
    /**
     * 施工内容及影响范围
     */
    private String fJwtdmids;
    /**
     * 施工内容及影响范围
     */
    private String fJwtdmmcs;
    /**
     * 施工内容及影响范围
     */
    private String fZhjtdmids;
    /**
     * 施工内容及影响范围
     */
    private String fZhjtdmmcs;
    /**
     * 施工内容及影响范围
     */
    private String fChwtdmids;
    /**
     * 施工内容及影响范围
     */
    private String fChwtdmmcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sgjh
     *
     * @mbg.generated Tue Oct 13 08:52:12 CST 2020
     */
    private static final long serialVersionUID = 1L;


}