package com.data.big.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Table(name = "trainloaction")
@Data
public class Trainloaction implements Serializable {
    /**
     * 主键id
     */
    @Id
    private String id;

    /**
     * 列车id
     */
    private String trainid;

    /**
     * 列车名称
     */
    private String trainname;

    /**
     * 摄像头定位点
     */
    private String ipclocationid;

    /**
     * 
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    private Date kssj;

    /**
     * 
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(
            pattern = "yyyy-MM-dd HH:mm:ss",
            timezone = "GMT+8"
    )
    private Date jssj;

    /**
     * 持续时间
     */
    private Integer sd;

    /**
     * 
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(
            pattern = "yyyy-MM-dd",
            timezone = "GMT+8"
    )
    private Date rq;

    /**
     * 
     */
    private String bz1;

    /**
     * 
     */
    private String bz2;

    /**
     * 
     */
    private String bz3;

    /**
     * 显示顺序
     */
    private Integer xssx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trainloaction
     *
     * @mbg.generated Thu Dec 10 09:59:15 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * 第几页
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;
    /**
     * 摄像头位置信息
     */
    @Transient
    private List<Ipcseelocation> ipcseelocationList;


}