package com.data.big.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.soap.Name;
import java.io.Serializable;
@Table(name = "trainloaction")
@Data
public class Trainloaction implements Serializable {
    /**
     * 主键id
     */
    @Id
    private String id;

    /**
     * 列车id
     */
    private String trainid;

    /**
     * 列车名称
     */
    private String trainname;

    /**
     * 摄像头定位点
     */
    private String ipclocationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trainloaction
     *
     * @mbg.generated Mon Dec 07 08:49:16 CST 2020
     */
    private static final long serialVersionUID = 1L;
    /**
     * 页编号
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;

}