package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "travel")
public class Travel implements Serializable {
    /**
     * id
     */
    @Id
    private String id;

    /**
     * 状态 0以消除 1以确认 2未处理 3暂缓处理 4 自动确认
     */
    private String status;

    /**
     * 设备编码
     */
    private String deptcode;

    /**
     * 创建时间
     */
    private String createtime;

    /**
     * 图片地址
     */
    private String imgPath;

    /**
     * IP
     */
    private String ip;

    /**
     * 告警id
 
     */
    private String alarmid;

    /**
     * 录像地址
     */
    private String vidPath;

    /**
     * 类型 1 yxbj:越线报警；2 pdcd:排队长度；3 dbrq:端部入侵； 4 rynx:人员逆行；5 klmd:客流密度； 6 cztdnx:出站通道逆行
     */
    private String alarmtype;

    /**
     * 报警类型名称
     */
    private String alarmname;

    /**
     * 摄像机名称
     */
    private String cameraname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travel
     *
     * @mbg.generated Thu Sep 24 09:37:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getDeptcode() {
        return deptcode;
    }

    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode == null ? null : deptcode.trim();
    }

    public String getCreatetime() {
        return createtime;
    }

    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    public String getImgPath() {
        return imgPath;
    }

    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    public String getAlarmid() {
        return alarmid;
    }

    public void setAlarmid(String alarmid) {
        this.alarmid = alarmid == null ? null : alarmid.trim();
    }

    public String getVidPath() {
        return vidPath;
    }

    public void setVidPath(String vidPath) {
        this.vidPath = vidPath == null ? null : vidPath.trim();
    }

    public String getAlarmtype() {
        return alarmtype;
    }

    public void setAlarmtype(String alarmtype) {
        this.alarmtype = alarmtype == null ? null : alarmtype.trim();
    }

    public String getAlarmname() {
        return alarmname;
    }

    public void setAlarmname(String alarmname) {
        this.alarmname = alarmname == null ? null : alarmname.trim();
    }

    public String getCameraname() {
        return cameraname;
    }

    public void setCameraname(String cameraname) {
        this.cameraname = cameraname == null ? null : cameraname.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", status=").append(status);
        sb.append(", deptcode=").append(deptcode);
        sb.append(", createtime=").append(createtime);
        sb.append(", imgPath=").append(imgPath);
        sb.append(", ip=").append(ip);
        sb.append(", alarmid=").append(alarmid);
        sb.append(", vidPath=").append(vidPath);
        sb.append(", alarmtype=").append(alarmtype);
        sb.append(", alarmname=").append(alarmname);
        sb.append(", cameraname=").append(cameraname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}