package com.data.big.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.List;

@Table(name = "video_upload")
@Data
public class VideoUpload implements Serializable {
    /**
     * 主键guid
     */
    @Id
    private String id;

    /**
     * 摄像头ID
     */
    private String ipcid;

    /**
     * 开始时间
     */
    private String kssj;

    /**
     * 结束时间
     */
    private String jssj;

    /**
     * 0未下载1已下载2上传中
 3已上传200问题任务
     */
    private String status;

    /**
     * 下载时间
     */
    private String loadtime;

    /**
     * 本地存储路径
     */
    private String path;

    /**
     * 文件名称
     */
    private String filename;

    /**
     * 文件ID
     */
    private String fileid;

    /**
     * 文件上传时间
     */
    private String uptime;

    /**
     * 备注
     */
    private String bz;

    /**
     * 视频类型名
     */
    private String videoType;

    /**
     * 告警id
     */
    private String alarmId;

    /**
     * 页编号
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;
    /**
     * 摄像机类
     */
    @Transient
    private Camera camera;
    /**
     * 视频标签类
     */
    @Transient
    private List<VideoTag> videoTag;
    /**
     * 摄像机标签类
     */
    @Transient
    private List<IpcTag> ipcTags;
    /**
     * 摄像机标签类
     */
    @Transient
    private List<VideoType> videoTypeList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_upload
     *
     * @mbg.generated Thu Nov 19 09:54:51 CST 2020
     */
    private static final long serialVersionUID = 1L;


}