package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

@Table(name = "video_tag")
public class VideoTag implements Serializable {
    /**
     * 
     */
    @Id
    private String id;

    /**
     * 摄像头ID
     */
    private String ipcid;

    /**
     * 视频任务类标签
     */
    private String tag;

    /**
     * 
     */
    private Date rktime;

    /**
     * 视频任务id 
     */
    private String videoFileId;

    /**
     * tag集合
     */
    @Transient
    private List<String> tags;
    /**
     * tag集合
     */
    @Transient
    private List<VideoFile> videoFiles;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_tag
     *
     * @mbg.generated Fri Nov 13 08:28:05 CST 2020
     */
    private static final long serialVersionUID = 1L;


    public List<VideoFile> getVideoFiles() {
        return videoFiles;
    }

    public void setVideoFiles(List<VideoFile> videoFiles) {
        this.videoFiles = videoFiles;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getIpcid() {
        return ipcid;
    }

    public void setIpcid(String ipcid) {
        this.ipcid = ipcid == null ? null : ipcid.trim();
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    public Date getRktime() {
        return rktime;
    }

    public void setRktime(Date rktime) {
        this.rktime = rktime;
    }

    public String getVideoFileId() {
        return videoFileId;
    }

    public void setVideoFileId(String videoFileId) {
        this.videoFileId = videoFileId == null ? null : videoFileId.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ipcid=").append(ipcid);
        sb.append(", tag=").append(tag);
        sb.append(", rktime=").append(rktime);
        sb.append(", videoFileId=").append(videoFileId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}