package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "video_file")
public class VideoFile implements Serializable {
    /**
     * 主键guid
     */
    @Id
    private String id;

    /**
     * 摄像头ID
     */
    private String ipcid;

    /**
     * 开始时间
     */
    private String kssj;

    /**
     * 结束时间
     */
    private String jssj;

    /**
     * 0未下载1已下载2上传中
 3已上传200问题任务
     */
    private String status;

    /**
     * 下载时间
     */
    private String loadtime;

    /**
     * 本地存储路径
     */
    private String path;

    /**
     * 文件名称
     */
    private String filename;

    /**
     * 文件ID
     */
    private String fileid;

    /**
     * 文件上传时间
     */
    private String uptime;

    /**
     * 备注
     */
    private String bz;

    /**
     * 视频类型名
     */
    private String videoType;

    /**
     * 告警id
     */
    private String alarmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_file
     *
     * @mbg.generated Tue Oct 13 09:00:43 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getIpcid() {
        return ipcid;
    }

    public void setIpcid(String ipcid) {
        this.ipcid = ipcid == null ? null : ipcid.trim();
    }

    public String getKssj() {
        return kssj;
    }

    public void setKssj(String kssj) {
        this.kssj = kssj == null ? null : kssj.trim();
    }

    public String getJssj() {
        return jssj;
    }

    public void setJssj(String jssj) {
        this.jssj = jssj == null ? null : jssj.trim();
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public String getLoadtime() {
        return loadtime;
    }

    public void setLoadtime(String loadtime) {
        this.loadtime = loadtime == null ? null : loadtime.trim();
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    public String getFileid() {
        return fileid;
    }

    public void setFileid(String fileid) {
        this.fileid = fileid == null ? null : fileid.trim();
    }

    public String getUptime() {
        return uptime;
    }

    public void setUptime(String uptime) {
        this.uptime = uptime == null ? null : uptime.trim();
    }

    public String getBz() {
        return bz;
    }

    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    public String getVideoType() {
        return videoType;
    }

    public void setVideoType(String videoType) {
        this.videoType = videoType == null ? null : videoType.trim();
    }

    public String getAlarmId() {
        return alarmId;
    }

    public void setAlarmId(String alarmId) {
        this.alarmId = alarmId == null ? null : alarmId.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", ipcid=").append(ipcid);
        sb.append(", kssj=").append(kssj);
        sb.append(", jssj=").append(jssj);
        sb.append(", status=").append(status);
        sb.append(", loadtime=").append(loadtime);
        sb.append(", path=").append(path);
        sb.append(", filename=").append(filename);
        sb.append(", fileid=").append(fileid);
        sb.append(", uptime=").append(uptime);
        sb.append(", bz=").append(bz);
        sb.append(", videoType=").append(videoType);
        sb.append(", alarmId=").append(alarmId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}