package com.data.big.model;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.util.Date;

@Table(name = "video_type")
@Slf4j
@Data
public class VideoType implements Serializable {
    /**
     * 
     */
    @Id
    private String id;

    /**
     * 摄像头ID
     */
    private String ipcid;

    /**
     * 视频任务类标签
     */
    private String tag;

    /**
     * 
     */
    private Date rktime;

    /**
     * 视频任务id 
     */
    private String videoFileId;
    /**
     * 页编号
     */
    @Transient
    private String pageIndex;
    /**
     * 每页个数
     */
    @Transient
    private String pageSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_type
     *
     * @mbg.generated Thu Nov 19 09:55:20 CST 2020
     */
    private static final long serialVersionUID = 1L;



}