package com.data.big.model;

import lombok.Data;

import javax.persistence.Id;
import javax.persistence.NamedNativeQueries;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "wxjh")
@Data
public class Wxjh implements Serializable {
    /**
     * id
     */
    @Id
    private String id;

    /**
     * 编制单位
     */
    private String bzdwmc;

    /**
     * 点内外(0点内 1点外 2超临修)
     */
    private String zylx;

    /**
     * 作业等级
     */
    private String zydj;

    /**
     * 作业日期
     */
    private String zyrq;

    /**
     * 作业时段
     */
    private String zysd;

    /**
     * 线名
     */
    private String xm;

    /**
     * 行别
     */
    private String xb;

    /**
     * 起始车站
     */
    private String qschzm;

    /**
     * 终止车站
     */
    private String zzchzm;

    /**
     * 作业起始里程
     */
    private String zyqslc;

    /**
     * 作业终止里程
     */
    private String zyzzlc;

    /**
     * 班次
     */
    private String banci;

    /**
     * 驻站防护员
     */
    private String zzfhr;

    /**
     * 工地防护员
     */
    private String gdfhr;

    /**
     * 远方防护员
     */
    private String yffhr;

    /**
     * 带班人
     */
    private String dbr;

    /**
     * 计划状态"-1驳回", "0计划上报", "1车间审批", "2段审批", "4工区执行", "5工单编制", "6完成反馈"	
     */
    private String sbztw;

    /**
     * 添加任务状态 0未添加 1以添加
     */
    private String status;

    /**
     * 作业项目
     */
    private String zyxm;
    /**
     * 施工内容及影响范围
     */
    private String fJwtdmids;
    /**
     * 施工内容及影响范围
     */
    private String fJwtdmmcs;
    /**
     * 施工内容及影响范围
     */
    private String fZhjtdmids;
    /**
     * 施工内容及影响范围
     */
    private String fZhjtdmmcs;
    /**
     * 施工内容及影响范围
     */
    private String fChwtdmids;
    /**
     * 施工内容及影响范围
     */
    private String fChwtdmmcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxjh
     *
     * @mbg.generated Tue Oct 13 08:57:55 CST 2020
     */
    private static final long serialVersionUID = 1L;


}