package com.data.big.model;

import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
@Table(name = "wxjh")
public class Wxjh implements Serializable {
    /**
     * id
     */
    @Id
    private String id;

    /**
     * 编制单位
     */
    private String bzdwmc;

    /**
     * 点内外(0点内 1点外 2超临修)
     */
    private String zylx;

    /**
     * 作业等级
     */
    private String zydj;

    /**
     * 作业项目
     */
    private String zyxm;

    /**
     * 作业日期
     */
    private String zyrq;

    /**
     * 作业时段
     */
    private String zysd;

    /**
     * 线名
     */
    private String xm;

    /**
     * 行别
     */
    private String xb;

    /**
     * 起始车站
     */
    private String qschzm;

    /**
     * 终止车站
     */
    private String zzchzm;

    /**
     * 作业起始里程
     */
    private String zyqslc;

    /**
     * 作业终止里程
     */
    private String zyzzlc;

    /**
     * 班次
     */
    private String banci;

    /**
     * 驻站防护员
     */
    private String zzfhr;

    /**
     * 工地防护员
     */
    private String gdfhr;

    /**
     * 远方防护员
     */
    private String yffhr;

    /**
     * 带班人
     */
    private String dbr;

    /**
     * 计划状态"-1驳回", "0计划上报", "1车间审批", "2段审批", "4工区执行", "5工单编制", "6完成反馈"	
     */
    private String sbztw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wxjh
     *
     * @mbg.generated Thu Sep 24 16:08:23 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getBzdwmc() {
        return bzdwmc;
    }

    public void setBzdwmc(String bzdwmc) {
        this.bzdwmc = bzdwmc == null ? null : bzdwmc.trim();
    }

    public String getZylx() {
        return zylx;
    }

    public void setZylx(String zylx) {
        this.zylx = zylx == null ? null : zylx.trim();
    }

    public String getZydj() {
        return zydj;
    }

    public void setZydj(String zydj) {
        this.zydj = zydj == null ? null : zydj.trim();
    }

    public String getZyxm() {
        return zyxm;
    }

    public void setZyxm(String zyxm) {
        this.zyxm = zyxm == null ? null : zyxm.trim();
    }

    public String getZyrq() {
        return zyrq;
    }

    public void setZyrq(String zyrq) {
        this.zyrq = zyrq == null ? null : zyrq.trim();
    }

    public String getZysd() {
        return zysd;
    }

    public void setZysd(String zysd) {
        this.zysd = zysd == null ? null : zysd.trim();
    }

    public String getXm() {
        return xm;
    }

    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    public String getXb() {
        return xb;
    }

    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    public String getQschzm() {
        return qschzm;
    }

    public void setQschzm(String qschzm) {
        this.qschzm = qschzm == null ? null : qschzm.trim();
    }

    public String getZzchzm() {
        return zzchzm;
    }

    public void setZzchzm(String zzchzm) {
        this.zzchzm = zzchzm == null ? null : zzchzm.trim();
    }

    public String getZyqslc() {
        return zyqslc;
    }

    public void setZyqslc(String zyqslc) {
        this.zyqslc = zyqslc == null ? null : zyqslc.trim();
    }

    public String getZyzzlc() {
        return zyzzlc;
    }

    public void setZyzzlc(String zyzzlc) {
        this.zyzzlc = zyzzlc == null ? null : zyzzlc.trim();
    }

    public String getBanci() {
        return banci;
    }

    public void setBanci(String banci) {
        this.banci = banci == null ? null : banci.trim();
    }

    public String getZzfhr() {
        return zzfhr;
    }

    public void setZzfhr(String zzfhr) {
        this.zzfhr = zzfhr == null ? null : zzfhr.trim();
    }

    public String getGdfhr() {
        return gdfhr;
    }

    public void setGdfhr(String gdfhr) {
        this.gdfhr = gdfhr == null ? null : gdfhr.trim();
    }

    public String getYffhr() {
        return yffhr;
    }

    public void setYffhr(String yffhr) {
        this.yffhr = yffhr == null ? null : yffhr.trim();
    }

    public String getDbr() {
        return dbr;
    }

    public void setDbr(String dbr) {
        this.dbr = dbr == null ? null : dbr.trim();
    }

    public String getSbztw() {
        return sbztw;
    }

    public void setSbztw(String sbztw) {
        this.sbztw = sbztw == null ? null : sbztw.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bzdwmc=").append(bzdwmc);
        sb.append(", zylx=").append(zylx);
        sb.append(", zydj=").append(zydj);
        sb.append(", zyxm=").append(zyxm);
        sb.append(", zyrq=").append(zyrq);
        sb.append(", zysd=").append(zysd);
        sb.append(", xm=").append(xm);
        sb.append(", xb=").append(xb);
        sb.append(", qschzm=").append(qschzm);
        sb.append(", zzchzm=").append(zzchzm);
        sb.append(", zyqslc=").append(zyqslc);
        sb.append(", zyzzlc=").append(zyzzlc);
        sb.append(", banci=").append(banci);
        sb.append(", zzfhr=").append(zzfhr);
        sb.append(", gdfhr=").append(gdfhr);
        sb.append(", yffhr=").append(yffhr);
        sb.append(", dbr=").append(dbr);
        sb.append(", sbztw=").append(sbztw);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}