package com.data.big.gw;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2020-09-30T14:58:20.416+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "GwaqscJxglService", 
                  wsdlLocation = "http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl",
                  targetNamespace = "http://services.itcmor.com") 
public class GwaqscJxglService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.itcmor.com", "GwaqscJxglService");
    public final static QName GwaqscJxglServiceHttpSoap11Endpoint = new QName("http://services.itcmor.com", "GwaqscJxglServiceHttpSoap11Endpoint");
    public final static QName GwaqscJxglServiceHttpEndpoint = new QName("http://services.itcmor.com", "GwaqscJxglServiceHttpEndpoint");
    public final static QName GwaqscJxglServiceHttpSoap12Endpoint = new QName("http://services.itcmor.com", "GwaqscJxglServiceHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GwaqscJxglService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GwaqscJxglService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GwaqscJxglService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GwaqscJxglService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public GwaqscJxglService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GwaqscJxglService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GwaqscJxglService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns GwaqscJxglServicePortType
     */
    @WebEndpoint(name = "GwaqscJxglServiceHttpSoap11Endpoint")
    public GwaqscJxglServicePortType getGwaqscJxglServiceHttpSoap11Endpoint() {
        return super.getPort(GwaqscJxglServiceHttpSoap11Endpoint, GwaqscJxglServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GwaqscJxglServicePortType
     */
    @WebEndpoint(name = "GwaqscJxglServiceHttpSoap11Endpoint")
    public GwaqscJxglServicePortType getGwaqscJxglServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(GwaqscJxglServiceHttpSoap11Endpoint, GwaqscJxglServicePortType.class, features);
    }


    /**
     *
     * @return
     *     returns GwaqscJxglServicePortType
     */
    @WebEndpoint(name = "GwaqscJxglServiceHttpEndpoint")
    public GwaqscJxglServicePortType getGwaqscJxglServiceHttpEndpoint() {
        return super.getPort(GwaqscJxglServiceHttpEndpoint, GwaqscJxglServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GwaqscJxglServicePortType
     */
    @WebEndpoint(name = "GwaqscJxglServiceHttpEndpoint")
    public GwaqscJxglServicePortType getGwaqscJxglServiceHttpEndpoint(WebServiceFeature... features) {
        return super.getPort(GwaqscJxglServiceHttpEndpoint, GwaqscJxglServicePortType.class, features);
    }


    /**
     *
     * @return
     *     returns GwaqscJxglServicePortType
     */
    @WebEndpoint(name = "GwaqscJxglServiceHttpSoap12Endpoint")
    public GwaqscJxglServicePortType getGwaqscJxglServiceHttpSoap12Endpoint() {
        return super.getPort(GwaqscJxglServiceHttpSoap12Endpoint, GwaqscJxglServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GwaqscJxglServicePortType
     */
    @WebEndpoint(name = "GwaqscJxglServiceHttpSoap12Endpoint")
    public GwaqscJxglServicePortType getGwaqscJxglServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(GwaqscJxglServiceHttpSoap12Endpoint, GwaqscJxglServicePortType.class, features);
    }

}
