package com.data.big.gw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2020-09-11T10:16:44.882+08:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "http://services.itcmor.com", name = "GwaqscJxglServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface GwaqscJxglServicePortType {

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getBhdata", output = "urn:getBhdataResponse")
    @RequestWrapper(localName = "getBhdata", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetBhdata")
    @WebMethod(action = "urn:getBhdata")
    @ResponseWrapper(localName = "getBhdataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetBhdataResponse")
    public String getBhdata(
        @WebParam(name = "flag", targetNamespace = "http://services.itcmor.com")
        String flag
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getQLdata", output = "urn:getQLdataResponse")
    @RequestWrapper(localName = "getQLdata", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetQLdata")
    @WebMethod(action = "urn:getQLdata")
    @ResponseWrapper(localName = "getQLdataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetQLdataResponse")
    public String getQLdata(
        @WebParam(name = "lineCode", targetNamespace = "http://services.itcmor.com")
        String lineCode,
        @WebParam(name = "xb", targetNamespace = "http://services.itcmor.com")
        String xb,
        @WebParam(name = "gjqs", targetNamespace = "http://services.itcmor.com")
        String gjqs,
        @WebParam(name = "gjzz", targetNamespace = "http://services.itcmor.com")
        String gjzz
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getCHZHdata", output = "urn:getCHZHdataResponse")
    @RequestWrapper(localName = "getCHZHdata", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetCHZHdata")
    @WebMethod(action = "urn:getCHZHdata")
    @ResponseWrapper(localName = "getCHZHdataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetCHZHdataResponse")
    public String getCHZHdata(
        @WebParam(name = "dwbh", targetNamespace = "http://services.itcmor.com")
        String dwbh,
        @WebParam(name = "lineCode", targetNamespace = "http://services.itcmor.com")
        String lineCode,
        @WebParam(name = "qslc", targetNamespace = "http://services.itcmor.com")
        String qslc,
        @WebParam(name = "zzlc", targetNamespace = "http://services.itcmor.com")
        String zzlc,
        @WebParam(name = "chzhdj", targetNamespace = "http://services.itcmor.com")
        String chzhdj,
        @WebParam(name = "zyb", targetNamespace = "http://services.itcmor.com")
        String zyb,
        @WebParam(name = "czbh", targetNamespace = "http://services.itcmor.com")
        String czbh,
        @WebParam(name = "xb", targetNamespace = "http://services.itcmor.com")
        String xb
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getSgjh", output = "urn:getSgjhResponse")
    @RequestWrapper(localName = "getSgjh", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetSgjh")
    @WebMethod(action = "urn:getSgjh")
    @ResponseWrapper(localName = "getSgjhResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetSgjhResponse")
    public String getSgjh(
        @WebParam(name = "qsrq", targetNamespace = "http://services.itcmor.com")
        String qsrq,
        @WebParam(name = "jsrq", targetNamespace = "http://services.itcmor.com")
        String jsrq
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getGgssData", output = "urn:getGgssDataResponse")
    @RequestWrapper(localName = "getGgssData", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetGgssData")
    @WebMethod(action = "urn:getGgssData")
    @ResponseWrapper(localName = "getGgssDataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetGgssDataResponse")
    public String getGgssData(
        @WebParam(name = "temp", targetNamespace = "http://services.itcmor.com")
        String temp
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getLjwclByGwdAndRq", output = "urn:getLjwclByGwdAndRqResponse")
    @RequestWrapper(localName = "getLjwclByGwdAndRq", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetLjwclByGwdAndRq")
    @WebMethod(action = "urn:getLjwclByGwdAndRq")
    @ResponseWrapper(localName = "getLjwclByGwdAndRqResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetLjwclByGwdAndRqResponse")
    public String getLjwclByGwdAndRq(
        @WebParam(name = "qsrq", targetNamespace = "http://services.itcmor.com")
        String qsrq,
        @WebParam(name = "zzrq", targetNamespace = "http://services.itcmor.com")
        String zzrq,
        @WebParam(name = "gwd", targetNamespace = "http://services.itcmor.com")
        String gwd
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getHcsj", output = "urn:getHcsjResponse")
    @RequestWrapper(localName = "getHcsj", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetHcsj")
    @WebMethod(action = "urn:getHcsj")
    @ResponseWrapper(localName = "getHcsjResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetHcsjResponse")
    public String getHcsj(
        @WebParam(name = "qsrq", targetNamespace = "http://services.itcmor.com")
        String qsrq,
        @WebParam(name = "jsrq", targetNamespace = "http://services.itcmor.com")
        String jsrq,
        @WebParam(name = "cxdj", targetNamespace = "http://services.itcmor.com")
        String cxdj
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getWxjh", output = "urn:getWxjhResponse")
    @RequestWrapper(localName = "getWxjh", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetWxjh")
    @WebMethod(action = "urn:getWxjh")
    @ResponseWrapper(localName = "getWxjhResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetWxjhResponse")
    public String getWxjh(
        @WebParam(name = "qsrq", targetNamespace = "http://services.itcmor.com")
        String qsrq,
        @WebParam(name = "jsrq", targetNamespace = "http://services.itcmor.com")
        String jsrq
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getSdjhData", output = "urn:getSdjhDataResponse")
    @RequestWrapper(localName = "getSdjhData", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetSdjhData")
    @WebMethod(action = "urn:getSdjhData")
    @ResponseWrapper(localName = "getSdjhDataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetSdjhDataResponse")
    public String getSdjhData(
        @WebParam(name = "temp", targetNamespace = "http://services.itcmor.com")
        String temp
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:list2xml", output = "urn:list2xmlResponse")
    @RequestWrapper(localName = "list2xml", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.List2Xml")
    @WebMethod(operationName = "list2xml", action = "urn:list2xml")
    @ResponseWrapper(localName = "list2xmlResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.List2XmlResponse")
    public com.data.big.gw.Element list2Xml(
        @WebParam(name = "list", targetNamespace = "http://services.itcmor.com")
        Object list,
        @WebParam(name = "element", targetNamespace = "http://services.itcmor.com")
                com.data.big.gw.Element element
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getTcjhData", output = "urn:getTcjhDataResponse")
    @RequestWrapper(localName = "getTcjhData", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetTcjhData")
    @WebMethod(action = "urn:getTcjhData")
    @ResponseWrapper(localName = "getTcjhDataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetTcjhDataResponse")
    public String getTcjhData(
        @WebParam(name = "temp", targetNamespace = "http://services.itcmor.com")
        String temp
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getHQdata", output = "urn:getHQdataResponse")
    @RequestWrapper(localName = "getHQdata", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetHQdata")
    @WebMethod(action = "urn:getHQdata")
    @ResponseWrapper(localName = "getHQdataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetHQdataResponse")
    public String getHQdata(
        @WebParam(name = "lineCode", targetNamespace = "http://services.itcmor.com")
        String lineCode,
        @WebParam(name = "xb", targetNamespace = "http://services.itcmor.com")
        String xb,
        @WebParam(name = "gjqs", targetNamespace = "http://services.itcmor.com")
        String gjqs,
        @WebParam(name = "gjzz", targetNamespace = "http://services.itcmor.com")
        String gjzz
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getSDdata", output = "urn:getSDdataResponse")
    @RequestWrapper(localName = "getSDdata", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetSDdata")
    @WebMethod(action = "urn:getSDdata")
    @ResponseWrapper(localName = "getSDdataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetSDdataResponse")
    public String getSDdata(
        @WebParam(name = "lineCode", targetNamespace = "http://services.itcmor.com")
        String lineCode,
        @WebParam(name = "xb", targetNamespace = "http://services.itcmor.com")
        String xb,
        @WebParam(name = "gjqs", targetNamespace = "http://services.itcmor.com")
        String gjqs,
        @WebParam(name = "gjzz", targetNamespace = "http://services.itcmor.com")
        String gjzz
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getJcjh", output = "urn:getJcjhResponse")
    @RequestWrapper(localName = "getJcjh", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetJcjh")
    @WebMethod(action = "urn:getJcjh")
    @ResponseWrapper(localName = "getJcjhResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetJcjhResponse")
    public String getJcjh(
        @WebParam(name = "qsrq", targetNamespace = "http://services.itcmor.com")
        String qsrq,
        @WebParam(name = "jsrq", targetNamespace = "http://services.itcmor.com")
        String jsrq,
        @WebParam(name = "jhlx", targetNamespace = "http://services.itcmor.com")
        String jhlx
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getXcbhData", output = "urn:getXcbhDataResponse")
    @RequestWrapper(localName = "getXcbhData", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetXcbhData")
    @WebMethod(action = "urn:getXcbhData")
    @ResponseWrapper(localName = "getXcbhDataResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetXcbhDataResponse")
    public String getXcbhData(
        @WebParam(name = "temp", targetNamespace = "http://services.itcmor.com")
        String temp
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getGwdLjwclByRq", output = "urn:getGwdLjwclByRqResponse")
    @RequestWrapper(localName = "getGwdLjwclByRq", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetGwdLjwclByRq")
    @WebMethod(action = "urn:getGwdLjwclByRq")
    @ResponseWrapper(localName = "getGwdLjwclByRqResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetGwdLjwclByRqResponse")
    public String getGwdLjwclByRq(
        @WebParam(name = "qsrq", targetNamespace = "http://services.itcmor.com")
        String qsrq,
        @WebParam(name = "zzrq", targetNamespace = "http://services.itcmor.com")
        String zzrq
    );

    @WebResult(name = "return", targetNamespace = "http://services.itcmor.com")
    @Action(input = "urn:getGjByZzjglx", output = "urn:getGjByZzjglxResponse")
    @RequestWrapper(localName = "getGjByZzjglx", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetGjByZzjglx")
    @WebMethod(action = "urn:getGjByZzjglx")
    @ResponseWrapper(localName = "getGjByZzjglxResponse", targetNamespace = "http://services.itcmor.com", className = "com.itcmor.services.GetGjByZzjglxResponse")
    public String getGjByZzjglx(
        @WebParam(name = "zzjg", targetNamespace = "http://services.itcmor.com")
        String zzjg
    );
}
