server:
  port: 12003


spring:
  datasource:
    username: admin
    password: 1qaz!QAZ
    #url: jdbc:mysql://10.3.78.209:13306/video_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    url: jdbc:mysql://127.0.0.1:13306/video_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000

  #MQ配置IP 端口
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.data.big.model

#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#mapper4 配置
mapper:
  mappers: com.data.big.base.BaseMapper
  not-empty: false
  identity: MYSQL

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR



bootshiro:
  enableEncryptPassword: false

sendFileCron:
  "0 0/5 * * * ?"

sendImgFileCron:
  "0 0/2 * * * ?"

getANBAO3:
  url: "http://10.3.64.10/video_aj/ssmisbdwebservice.asmx"
  #从右到左 表示 年 月 日 时 分 秒    0 0 0/1 * * ? 表示每小时0分0秒执行一次     0 20 0 0/1 * ? 表示每天0点20分0秒 执行
  # 如果 是按每天执行一次 系统默认查询前一天数据  如果按小时执行 根据执行间隔小时数 查询前几小时数据
  cron: "0 30 01 */1 * ?"
  xm: "京包客专"
  lj: "路局"
  name: "VIDEO_AJ"   #用户名密码


#京张综合视频 摄像机资产信息 url
sendGetCameraInfo:
  url: "http://10.3.114.8:16559/nis/GetCameraInfo"
  cron: "0 20 0 0/1 * ?"
#京张综合视频 节点信息 url
sendGetNodeInfo:
  url: "http://10.3.114.8:16559/nis/GetNodeInfo"
  cron: "0 30 0 0/1 * ?"
#京张综合视频 服务器产信息 url
sendGetServerInfo:
  url: "http://10.3.114.8:16559/nis/GetServerInfo"
  cron: "0 40 0 0/1 * ?"
#京张综合视频 磁盘资产信息 url
sendGetDiskInfo:
  url: "http://10.3.114.8:16559/nis/GetDiskInfo"
  cron: "0 50 0 0/1 * ?"
#京张综合视频 交换机资产信息 url
sendGetSwitchInfo:
  url: "http://10.3.114.8:16559/nis/GetSwitchInfo"
  cron: "0 0 1 0/1 * ?"


#摄像机告警
sendGetCameraAlarm:
  url: "http://10.3.114.8:16559/nis/GetCameraAlarm"
  cron: "0 10 1 0/1 * ?"
#摄像机状态
sendGetCameraStatus:
  url: "http://10.3.114.8:16559/nis/GetCameraStatus"
  cron: "0 20 1 0/1 * ?"
#视频服务器告警
sendGetServerAlarm:
  url: "http://10.3.114.8:16559/nis/GetServerAlarm"
  cron: "0 30 1 0/1 * ?"
#视频服务器状态
sendGetServerStatus:
  url: "http://10.3.114.8:16559/nis/GetServerStatus"
  cron: "0 40 1 0/1 * ?"
#视频磁盘阵列告警
sendGetDiskAlarm:
  url: "http://10.3.114.8:16559/nis/GetDiskAlarm"
  cron: "0 50 1 0/1 * ?"
#视频磁盘阵列状态
sendGeDiskStatus:
  url: "http://10.3.114.8:16559/nis/GeDiskStatus"
  cron: "0 10 2 0/1 * ?"
#交换机告警
sendGetSwitchAlarm:
  url: "http://10.3.114.8:16559/nis/GetSwitchAlarm"
  cron: "0 20 2 0/1 * ?"
#交换机状态
sendGetSwitchStatus:
  url: "http://10.3.114.8:16559/nis/GetSwitchStatus"
  cron: "0 30 2 0/1 * ?"
#智能分析告警
sendGetIVSAlarm:
  url: "http://10.3.114.8:16559/nis/GetIVSAlarm"
  cron: "0 40 2 0/1 * ?"

alarmSelectTime:
  #从右到左 表示 年 月 日 时 分 秒    0 0 0/1 * * ? 表示每小时0分0秒执行一次     0 10 0 0/1 * ？ 表示每天0点10分0秒 执行
  # 如果 是按每天执行一次 系统默认查询前一天数据  如果按小时执行 根据执行间隔小时数 查询前几小时数据
  cron: "0 0 0/1 * * ?"


#执行定时查询任务    每5分钟查询一次
queryTaskTime: "0 0/5 * * * ?"



#向大数据中心发送数据
#发送视频文件
sendFileUrl: "http://10.3.78.188:1280/file-access/v1/tlzhspjkxtVgen"
token: "0e4e6ae9351e5d657b63406716ca2e9a"
fid: "1738"
saveFileUrl: "D:/fileUpload/"
#发送摄像头资产信息
sendAddTableUrl: "http://10.3.78.188:1280/data-access/v1/auto_tlzhspjkxtjghsj?tableName=ipc"
Authorization: "027ade7c3843cf0fc322033e89ba9a59"





#防灾配置
netty:
  #是否启动防灾客户端
  startOrNot: "true"
  host: "10.3.91.181"
  #host: "127.0.0.1"
  port: "11029"
  version: "010101"  #版本号v1.1.1 转成 010101
  nameAndPassword: "<JingWei_GongDianGong,JingWei_GongDianGong>"  #用户名密码
#防灾webservice
fz:
  url: "http://10.3.97.162:11029/ws/bigdata?wsdl"
  userName: "bigdata"
  passWord: "bigData@217"
  cron: "0 10 */2 * * ?"

#公务配置
gw:
  wsdlUrl: "http://10.3.136.225:8000/AqscWebMIS/services/GwaqscJxglService?wsdl"
  //wsdlNamespace: "http://webService.big.data.com/"
  wsdlNamespace: "http://services.itcmor.com/"
  wsdlName: "GwaqscJxglService"
  cron: "0 30 */5 * * ?"

#旅服
lf:
  url: "http://10.67.69.189/warningDataOperation/queryCurrentDayWarningData"
  #url: "http://127.0.0.1:8088/fdCon/queryCurrentDayWarningData"
  #保存文件地址
  saveAddress: "lf"
  cron: "0 40 */3 * * ?"




#.调用实时、历史视频（VideoPlayOpen）
videoPlayOpenUrl: "http://10.3.78.166:11005/VideoPlayOpen"

#用户登陆token失效时长 单位分钟
user:
  #是否启动使用token认证功能
  tokenEnable: "flase"
  tokenOutTime: 10